[package]
name = "username/zipshot"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.7"
React = "jsdotlua/react-roblox@^17.0.2"
Maid = "devsparkle/maid@^1.0.0"
Promise = "evaera/promise@^4.0.0"

[server_dependencies]
ProfileService = "brittonfischer/profileservice@^1.0.0"
